ASPNET4.5.MVC5.RealTime AppWithSignalR/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPNET4._5.MVC5.RealTime_AppWithSignalR.Controllers
{
    public class AdminHomeController : Controller
    {
        // GET: AdminHome
        public ActionResult Index()
        {
            return View();
        }
    }
}

ASPNET4.5.MVC5.RealTime AppWithSignalR/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPNET4._5.MVC5.RealTime_AppWithSignalR.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }
    }
}

ASPNET4.5.MVC5.RealTime AppWithSignalR/Controllers/FrontHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPNET4._5.MVC5.RealTime_AppWithSignalR.Controllers
{
    public class FrontHomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

ASPNET4.5.MVC5.RealTime AppWithSignalR/Controllers/FrontLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPNET4._5.MVC5.RealTime_AppWithSignalR.Controllers
{
    public class FrontLoginController : Controller
    {
        // GET: FrontLogin
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Test_Login()
        {           
            return RedirectToAction("Index", "AdminHome");
        }
    }
}

ASPNET4.5.MVC5.RealTime AppWithSignalR/Views/AdminHome/Index.cshtml
@{
    ViewBag.Title = "Admin Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Dashboard Index</h2>

ASPNET4.5.MVC5.RealTime AppWithSignalR/Views/FrontHome/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_FrontLayout.cshtml";
}

<h2>Index</h2>

ASPNET4.5.MVC5.RealTime AppWithSignalR/Views/FrontLogin/Index.cshtml
@{
    Layout = null;
    var _Template_Path = "~/Content/admin-login/";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Login Form</title>
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href="@Url.Content(_Template_Path + "css/styles.css")" rel="stylesheet">
</head>
<body>
    <!--login modal-->
    <div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h1 class="text-center">Login</h1>
                </div>
                <div class="modal-body">
                    <form  method="post" action="@Url.Action("Test_Login", "FrontLogin")" class="form col-md-12 center-block">
                        <div class="form-group">
                            <input type="text" class="form-control input-lg" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control input-lg" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary btn-lg btn-block">Sign In</button>
                            <span class="pull-right"><a href="#">Register</a></span><span><a href="#">Need help?</a></span>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <div class="col-md-12" >
                        <button class="btn" data-dismiss="modal" aria-hidden="true" onclick="location.href='@Url.Action("Index", "FrontHome")'">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- script references -->
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ASPNET4.5.MVC5.RealTime AppWithSignalR/Views/Shared/_FrontLayout.cshtml
@{
    var _Template_Path = "~/Content/front/"; 
}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title - Learn Blog</title>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <!-- Custom CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="@Url.Content(_Template_Path + "css/clean-blog.min.css")" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />


    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "FrontLogin")">Administrator</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('@Url.Content(_Template_Path + "images/NMSConceptArtWallpap.png")')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Learn Blog</h1>
                        <hr class="small">
                        <span class="subheading">Learn How to Blog Successfully</span>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <div class="container body-content">
        @RenderBody()
        <hr />

        <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <ul class="list-inline text-center">
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; @DateTime.Now.Year - My ASP.NET Application SignalR</p>
                    </div>
                </div>
            </div>
        </footer>

    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


    <!-- Custom Theme JavaScript -->
    <script src="@Url.Content(_Template_Path + "js/clean-blog.min.js")"></script>

</body>
</html>